version: '3.9'
networks:
  cassandra:
services:
  cassandra-node-1:
    image: cassandra:4.0.7
    container_name: cassandra-node-1
    hostname: cassandra-node-1
    networks:
      - cassandra
    ports:
      - "9042:9042"
    volumes:
      - /tmp/data/cassandra-node-1:/var/lib/cassandra
    environment:
      CASSANDRA_SEEDS: "cassandra-node-1,cassandra-node-2,cassandra-node-3,cassandra-node-4,cassandra-node-5,cassandra-node-6"
      CASSANDRA_CLUSTER_NAME: CassandraCluster
      MAX_HEAP_SIZE: 1G
      HEAP_NEWSIZE: 200M

  cassandra-node-2:
    image: cassandra:4.0.7
    container_name: cassandra-node-2
    hostname: cassandra-node-2
    networks:
      - cassandra
    ports:
      - "9043:9042"
    volumes:
      - /tmp/data/cassandra-node-2:/var/lib/cassandra
    environment:
      CASSANDRA_SEEDS: "cassandra-node-1,cassandra-node-2,cassandra-node-3,cassandra-node-4,cassandra-node-5,cassandra-node-6"
      CASSANDRA_CLUSTER_NAME: CassandraCluster
      MAX_HEAP_SIZE: 1G
      HEAP_NEWSIZE: 200M
    depends_on:
      - cassandra-node-1

  cassandra-node-3:
    image: cassandra:4.0.7
    container_name: cassandra-node-3
    hostname: cassandra-node-3
    networks:
      - cassandra
    ports:
      - "9044:9042"
    volumes:
      - /tmp/data/cassandra-node-3:/var/lib/cassandra
    environment:
      CASSANDRA_SEEDS: "cassandra-node-1,cassandra-node-2,cassandra-node-3,cassandra-node-4,cassandra-node-5,cassandra-node-6"
      CASSANDRA_CLUSTER_NAME: CassandraCluster
      MAX_HEAP_SIZE: 1G
      HEAP_NEWSIZE: 200M
    depends_on:
     - cassandra-node-2

  cassandra-node-4:
    image: cassandra:4.0.7
    container_name: cassandra-node-4
    hostname: cassandra-node-4
    networks:
      - cassandra
    ports:
      - "9045:9042"
    volumes:
      - /tmp/data/cassandra-node-4:/var/lib/cassandra
    environment:
      CASSANDRA_SEEDS: "cassandra-node-1,cassandra-node-2,cassandra-node-3,cassandra-node-4,cassandra-node-5,cassandra-node-6"
      CASSANDRA_CLUSTER_NAME: CassandraCluster
      MAX_HEAP_SIZE: 1G
      HEAP_NEWSIZE: 200M
    depends_on:
     - cassandra-node-3


  cassandra-node-5:
    image: cassandra:4.0.7
    container_name: cassandra-node-5
    hostname: cassandra-node-5
    networks:
      - cassandra
    ports:
      - "9046:9042"
    volumes:
      - /tmp/data/cassandra-node-5:/var/lib/cassandra
    environment:
      CASSANDRA_SEEDS: "cassandra-node-1,cassandra-node-2,cassandra-node-3,cassandra-node-4,cassandra-node-5,cassandra-node-6"
      CASSANDRA_CLUSTER_NAME: CassandraCluster
      MAX_HEAP_SIZE: 1G
      HEAP_NEWSIZE: 200M
    depends_on:
     - cassandra-node-4

  cassandra-node-6:
    image: cassandra:4.0.7
    container_name: cassandra-node-6
    hostname: cassandra-node-6
    networks:
      - cassandra
    ports:
      - "9047:9042"
    volumes:
      - /tmp/data/cassandra-node-6:/var/lib/cassandra
    environment:
      CASSANDRA_SEEDS: "cassandra-node-1,cassandra-node-2,cassandra-node-3,cassandra-node-4,cassandra-node-5,cassandra-node-6"
      CASSANDRA_CLUSTER_NAME: CassandraCluster
      MAX_HEAP_SIZE: 1G
      HEAP_NEWSIZE: 200M
    depends_on:
     - cassandra-node-5