version: '2' 
services: 
  redis-node-0:
    image: docker.io/bitnami/redis:7.0
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL 
    ports:
      - '6379:6379' 
    volumes:
      - 'redis_data-0:/bitnami/redis/data'
  redis-node-1:
    image: docker.io/bitnami/redis:7.0
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL 
    ports:
      - '6380:6380' 
    volumes:
      - 'redis_data-1:/bitnami/redis/data'
volumes:
  redis_data-0:
    driver: local
  redis_data-1:
    driver: local